//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendService) DeepCopyInto(out *BackendService) {
	*out = *in
	out.Port = in.Port
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendService.
func (in *BackendService) DeepCopy() *BackendService {
	if in == nil {
		return nil
	}
	out := new(BackendService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrontendService) DeepCopyInto(out *FrontendService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrontendService.
func (in *FrontendService) DeepCopy() *FrontendService {
	if in == nil {
		return nil
	}
	out := new(FrontendService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPConfigMap) DeepCopyInto(out *TCPConfigMap) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPConfigMap.
func (in *TCPConfigMap) DeepCopy() *TCPConfigMap {
	if in == nil {
		return nil
	}
	out := new(TCPConfigMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPIngressMapping) DeepCopyInto(out *TCPIngressMapping) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPIngressMapping.
func (in *TCPIngressMapping) DeepCopy() *TCPIngressMapping {
	if in == nil {
		return nil
	}
	out := new(TCPIngressMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCPIngressMapping) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPIngressMappingList) DeepCopyInto(out *TCPIngressMappingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TCPIngressMapping, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPIngressMappingList.
func (in *TCPIngressMappingList) DeepCopy() *TCPIngressMappingList {
	if in == nil {
		return nil
	}
	out := new(TCPIngressMappingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TCPIngressMappingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPIngressMappingSpec) DeepCopyInto(out *TCPIngressMappingSpec) {
	*out = *in
	out.BackendService = in.BackendService
	if in.FrontendService != nil {
		in, out := &in.FrontendService, &out.FrontendService
		*out = new(FrontendService)
		**out = **in
	}
	if in.TCPConfigMap != nil {
		in, out := &in.TCPConfigMap, &out.TCPConfigMap
		*out = new(TCPConfigMap)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPIngressMappingSpec.
func (in *TCPIngressMappingSpec) DeepCopy() *TCPIngressMappingSpec {
	if in == nil {
		return nil
	}
	out := new(TCPIngressMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPIngressMappingStatus) DeepCopyInto(out *TCPIngressMappingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPIngressMappingStatus.
func (in *TCPIngressMappingStatus) DeepCopy() *TCPIngressMappingStatus {
	if in == nil {
		return nil
	}
	out := new(TCPIngressMappingStatus)
	in.DeepCopyInto(out)
	return out
}
